# Generated by Django 2.0.6 on 2018-10-23 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Face_check_results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_action_user', models.CharField(max_length=255, null=True, verbose_name='执行者')),
                ('face_check_image_width', models.FloatField(null=True, verbose_name='图片宽度')),
                ('face_check_image_height', models.FloatField(null=True, verbose_name='图片高度')),
                ('face_check_gender', models.IntegerField(null=True, verbose_name='性别')),
                ('face_check_age', models.IntegerField(null=True, verbose_name='年龄')),
                ('face_check_expression', models.IntegerField(null=True, verbose_name='笑容')),
                ('face_check_glass', models.CharField(max_length=20, null=True, verbose_name='眼镜')),
                ('face_check_pitch', models.IntegerField(null=True, verbose_name='上下偏移')),
                ('face_check_yaw', models.IntegerField(null=True, verbose_name='左右偏移')),
                ('face_check_beauty', models.IntegerField(null=True, verbose_name='颜值魅力')),
                ('face_check_width', models.FloatField(null=True, verbose_name='脸部宽度')),
                ('face_check_height', models.FloatField(null=True, verbose_name='脸部高度')),
                ('face_check_results_status', models.IntegerField(default=0, verbose_name='检测结果')),
                ('ctime', models.DateTimeField(auto_now=True, verbose_name='操作时间')),
            ],
            options={
                'verbose_name_plural': '人脸检测结果',
                'db_table': 'Face_check_results',
                'verbose_name': '人脸检测结果',
            },
        ),
        migrations.CreateModel(
            name='Face_core_body_results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_action_user', models.CharField(max_length=255, null=True, verbose_name='上传者')),
                ('face_id_card_name', models.CharField(max_length=255, null=True, verbose_name='姓名')),
                ('face_id_card', models.CharField(max_length=255, null=True, verbose_name='身份证号码')),
                ('face_similarity', models.FloatField(null=True, verbose_name='验证结果')),
                ('face_core_body_results_status', models.IntegerField(default=0, verbose_name='检测结果')),
                ('ctime', models.DateTimeField(auto_now=True, verbose_name='完成时间')),
            ],
            options={
                'verbose_name_plural': '人脸对比',
                'db_table': 'Face_core_body_results',
                'verbose_name': '人脸对比',
            },
        ),
        migrations.CreateModel(
            name='Face_diff_results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_action_user', models.CharField(max_length=255, null=True, verbose_name='上传者')),
                ('face_similarity', models.FloatField(null=True, verbose_name='相似度')),
                ('face_diff_results_status', models.IntegerField(default=0, verbose_name='检测结果')),
                ('ctime', models.DateTimeField(auto_now=True, verbose_name='完成时间')),
            ],
            options={
                'verbose_name_plural': '人脸对比',
                'db_table': 'Face_diff_results',
                'verbose_name': '人脸对比',
            },
        ),
        migrations.CreateModel(
            name='Face_images_upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(error_messages={'invalid': '名称重复.'}, max_length=255, null=True, unique=True, verbose_name='图片名称')),
                ('upload_name', models.CharField(max_length=255, null=True, verbose_name='上传者')),
                ('face_action_type', models.IntegerField(choices=[(0, '人脸检测'), (1, '人脸对比'), (2, '人脸核身')], verbose_name='识别动作')),
                ('face_image_path1', models.ImageField(blank=True, null=True, upload_to='upload/%Y%m%d62872', verbose_name='上传照片')),
                ('face_image_path2', models.ImageField(blank=True, null=True, upload_to='upload/%Y%m%d949', verbose_name='对比照片')),
                ('face_action_status', models.IntegerField(default=0, verbose_name='识别动作')),
                ('ID_card_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='姓名')),
                ('ID_card', models.CharField(blank=True, max_length=255, null=True, verbose_name='身份证号码')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '人脸识别',
                'ordering': ['-ctime'],
                'verbose_name': '人脸识别',
                'permissions': {('read_uploadimages', '只读操作'), ('cmd_uploadimages', '上传操作')},
                'db_table': 'Face_images_upload',
            },
        ),
        migrations.AddField(
            model_name='face_diff_results',
            name='face_image_upload_relation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='face_diff', to='face.Face_images_upload', verbose_name='上传ID'),
        ),
        migrations.AddField(
            model_name='face_core_body_results',
            name='face_image_upload_relation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='face_core_body', to='face.Face_images_upload', verbose_name='上传ID'),
        ),
        migrations.AddField(
            model_name='face_check_results',
            name='face_image_upload_relation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='face', to='face.Face_images_upload', verbose_name='上传ID'),
        ),
    ]
