# Generated by Django 2.0.6 on 2018-09-11 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ocr_images_upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(error_messages={'invalid': '名称重复.'}, max_length=255, null=True, unique=True, verbose_name='图片名称')),
                ('upload_name', models.CharField(max_length=255, null=True, verbose_name='上传者')),
                ('ocr_action_type', models.IntegerField(choices=[(0, '身份证'), (1, '名片'), (2, '银行卡')], verbose_name='识别动作')),
                ('ocr_image_path', models.FileField(blank=True, null=True, upload_to='upload/%Y%m%d56156', verbose_name='图像路径')),
                ('ocr_action_status', models.IntegerField(default=0, verbose_name='识别动作')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'OCR上传',
                'ordering': ['-ctime'],
                'db_table': 'Ocr_images_upload',
                'verbose_name_plural': 'OCR上传',
            },
        ),
    ]
