# Generated by Django 2.0.6 on 2018-09-11 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0002_auto_20180911_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocr_images_upload',
            name='ocr_action_status',
            field=models.IntegerField(default=0, verbose_name='识别对象'),
        ),
        migrations.AlterField(
            model_name='ocr_images_upload',
            name='ocr_image_path',
            field=models.FileField(blank=True, null=True, upload_to='upload/%Y%m%d34384', verbose_name='图像路径'),
        ),
    ]
