# Generated by Django 2.0.6 on 2018-09-11 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0003_auto_20180911_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocr_images_upload',
            name='ocr_image_path1',
            field=models.FileField(blank=True, null=True, upload_to='upload/%Y%m%d9266', verbose_name='身份证反面'),
        ),
        migrations.AlterField(
            model_name='ocr_images_upload',
            name='ocr_image_path',
            field=models.FileField(blank=True, null=True, upload_to='upload/%Y%m%d86984', verbose_name='图像路径'),
        ),
    ]
